#!/usr/bin/env bash
# PostToolUse hook: gh pr create 실행 후 커버리지 + 번들 사이즈 + 벤치마크를 PR 코멘트로 게시
set -euo pipefail

# ── stdin JSON 파싱 ──────────────────────────────────────────────────────────
INPUT=$(cat)

if command -v jq &>/dev/null; then
  CMD=$(echo "$INPUT" | jq -r '.tool_input.command // ""')
else
  CMD=$(echo "$INPUT" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('tool_input',{}).get('command',''))" 2>/dev/null || echo "")
fi

# gh pr create 가 포함된 명령이 아니면 종료
if [[ "$CMD" != *"gh pr create"* ]]; then
  exit 0
fi

# ── PR 번호 조회 ──────────────────────────────────────────────────────────────
PR_NUMBER=$(gh pr view --json number -q .number 2>/dev/null || echo "")
if [[ -z "$PR_NUMBER" ]]; then
  echo "[post-pr-coverage] PR 번호를 가져올 수 없습니다. 종료합니다." >&2
  exit 0
fi

# ── 커버리지 실행 ─────────────────────────────────────────────────────────────
COVERAGE_OUTPUT=""
if COVERAGE_OUTPUT=$(pnpm test:coverage 2>&1); then
  # text 리포터 테이블만 추출 (────── 구분선이 있는 블록)
  COVERAGE_TABLE=$(echo "$COVERAGE_OUTPUT" | grep -A 9999 "^-\{3,\}" | head -30 || echo "$COVERAGE_OUTPUT" | tail -20)
else
  COVERAGE_TABLE="⚠️ 커버리지 측정 실패"$'\n'"$(echo "$COVERAGE_OUTPUT" | tail -5)"
fi

# ── 빌드 + 번들 사이즈 측정 ───────────────────────────────────────────────────
BUNDLE_TABLE=""
if pnpm build &>/dev/null; then
  BUNDLE_TABLE="| 파일 | 크기 |"$'\n'"|------|------|"
  for f in packages/*/dist/*.{js,mjs} 2>/dev/null; do
    [[ -f "$f" ]] || continue
    SIZE_BYTES=$(wc -c < "$f")
    SIZE_KB=$(awk "BEGIN {printf \"%.1f KB\", $SIZE_BYTES/1024}")
    BUNDLE_TABLE+=$'\n'"| \`$f\` | $SIZE_KB |"
  done
else
  BUNDLE_TABLE="⚠️ 빌드 실패"
fi

# ── 벤치마크 실행 ─────────────────────────────────────────────────────────────
BENCH_OUTPUT=""
if BENCH_OUTPUT=$(pnpm bench 2>&1); then
  BENCH_RESULT=$(echo "$BENCH_OUTPUT" | grep -E "(bench|ops/sec|✓|×)" | head -20 || echo "$BENCH_OUTPUT" | tail -20)
else
  BENCH_RESULT="⚠️ 벤치마크 실패"$'\n'"$(echo "$BENCH_OUTPUT" | tail -5)"
fi

# ── 코멘트 조립 ──────────────────────────────────────────────────────────────
COMMENT=$(cat <<EOF
## 🧪 Test Coverage

\`\`\`
$COVERAGE_TABLE
\`\`\`

## 📦 Bundle Size

$BUNDLE_TABLE

## ⚡ Benchmark

\`\`\`
$BENCH_RESULT
\`\`\`

---
🤖 Generated by jump-section AI Pipeline
EOF
)

# ── PR 코멘트 게시 ─────────────────────────────────────────────────────────────
gh pr comment "$PR_NUMBER" --body "$COMMENT"
echo "[post-pr-coverage] PR #$PR_NUMBER 에 코멘트를 게시했습니다."
